// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-SiY8urHDs_Dr9GZ6yXSG8PMUY7Db8g',
    appId: '1:988731721904:web:812c7c896dbf103ce35375',
    messagingSenderId: '988731721904',
    projectId: 'athar-973cd',
    authDomain: 'athar-973cd.firebaseapp.com',
    storageBucket: 'athar-973cd.firebasestorage.app',
    measurementId: 'G-YL96NBQ8M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwM9Qi1rUzzKCnqmgQzPJbuGOYNuShP0w',
    appId: '1:988731721904:android:2abc42c6a2dff58ae35375',
    messagingSenderId: '988731721904',
    projectId: 'athar-973cd',
    storageBucket: 'athar-973cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnuJqXNvEHsfubeiMIzqiU7y1vzZBx6QQ',
    appId: '1:988731721904:ios:fb1a613796e47141e35375',
    messagingSenderId: '988731721904',
    projectId: 'athar-973cd',
    storageBucket: 'athar-973cd.firebasestorage.app',
    iosClientId: '988731721904-rhb65vr9qhme4r9gtti713ng7jc3ll87.apps.googleusercontent.com',
    iosBundleId: 'com.example.athar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnuJqXNvEHsfubeiMIzqiU7y1vzZBx6QQ',
    appId: '1:988731721904:ios:fb1a613796e47141e35375',
    messagingSenderId: '988731721904',
    projectId: 'athar-973cd',
    storageBucket: 'athar-973cd.firebasestorage.app',
    iosClientId: '988731721904-rhb65vr9qhme4r9gtti713ng7jc3ll87.apps.googleusercontent.com',
    iosBundleId: 'com.example.athar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh-SiY8urHDs_Dr9GZ6yXSG8PMUY7Db8g',
    appId: '1:988731721904:web:c92a39d239e1c049e35375',
    messagingSenderId: '988731721904',
    projectId: 'athar-973cd',
    authDomain: 'athar-973cd.firebaseapp.com',
    storageBucket: 'athar-973cd.firebasestorage.app',
    measurementId: 'G-G5BXNSHDBS',
  );
}
